"""001_initial_schema

Revision ID: e328b921ead2
Revises:
Create Date: 2026-04-29 21:19:40.494854

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e328b921ead2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("settings_overrides", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("progress_done", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("current_item", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("native_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_languages", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active_target_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("auto_generate_audio", sa.Boolean(), nullable=False),
        sa.Column("auto_generate_images", sa.Boolean(), nullable=False),
        sa.Column("default_practice_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cards_per_session", sa.Integer(), nullable=False),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_word", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("translation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("forms", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("example_sentences", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("audio_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("personal_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image_skipped", sa.Boolean(), nullable=False),
        sa.Column("card_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=True),
        sa.Column("target_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stability", sa.Float(), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("due", sa.DateTime(), nullable=False),
        sa.Column("last_review", sa.DateTime(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("fsrs_state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cards_deck_id"), "cards", ["deck_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.Column("stability_after", sa.Float(), nullable=False),
        sa.Column("difficulty_after", sa.Float(), nullable=False),
        sa.Column("fsrs_state_after", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reps_after", sa.Integer(), nullable=False),
        sa.Column("lapses_after", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_card_id"), "reviews", ["card_id"], unique=False)
    # Additional performance indexes not detected by autogenerate
    op.create_index("ix_cards_due", "cards", ["due"], unique=False)
    op.create_index("ix_reviews_reviewed_at", "reviews", ["reviewed_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reviews_reviewed_at", table_name="reviews")
    op.drop_index(op.f("ix_reviews_card_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_cards_due", table_name="cards")
    op.drop_index(op.f("ix_cards_deck_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_table("settings")
    op.drop_table("jobs")
    op.drop_table("decks")
    # ### end Alembic commands ###
